services:
  - type: web
    name: quranapp
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
    autoDeploy: true
    numInstances: 1

databases:
  - name: quranapp-mongo
    databaseName: quranapp
    plan: starter
    region: oregon